name = "subhub"
main = "src/worker.ts"
compatibility_date = "2023-01-01"

# KV 命名空间
kv_namespaces = [
  { binding = "USERS_KV", id = "your-kv-id-here" }
]

# 环境变量（本地开发用）
[vars]
ADMIN_KEY = "changeme"
JWT_SECRET = "changeme"